apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sillai-in-tls
spec:
  secretName: sillai-in
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sillai.in
  dnsNames:
    - sillai.in
    - www.sillai.in
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sillai.in
          - www.sillai.in